### ISSUE TITLE
Heroku deployment is missing libddwaf.so

### ISSUE THREAD

**Issue by nertzy** [DataDog/libddwaf-rb#32]
In our Gemfile we have:
```ruby
group :test, :production do
  gem "ddtrace", require: "ddtrace/auto_instrument"
  gem "dogstatsd-ruby"
end
```

We are deploying to Heroku and using the datadog buildpack.

When our application boots up, it is unable to find `libddwaf.so`.

> E, [2023-06-06T22:21:11.909212 #2] ERROR -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/3.2.0/gems/ddtrace-1.12.0/lib/datadog/appsec/processor.rb:121:in `rescue in require_libddwaf') libddwaf failed to load,installed platform: ruby ruby platforms: ["ruby", "x86_64-linux"] error: #<LoadError: Could not open library '/app/vendor/bundle/ruby/3.2.0/gems/libddwaf-1.9.0.0.0/lib/datadog/appsec/../../../vendor/libddwaf/libddwaf-1.9.0-linux-gnu-x86_64/lib/libddwaf.so': /app/vendor/bundle/ruby/3.2.0/gems/libddwaf-1.9.0.0.0/lib/datadog/appsec/../../../vendor/libddwaf/libddwaf-1.9.0-linux-gnu-x86_64/lib/libddwaf.so: cannot open shared object file: No such file or directory>

I am not sure why the Heroku build process is failing to get the `.so` to the right location.

I can `heroku ps:exec` into one of our dynos and see that the `/app/vendor/bundle/ruby/3.2.0/gems/libddwaf-1.9.0.0.0/lib/datadog/appsec/../../../vendor/libddwaf` directory is not present.

**Comment by GustavoCaso** [comment]
Good morning @nertzy. Thanks for opening the issue. 

Have you tried https://github.com/DataDog/dd-trace-rb/issues/2652#issuecomment-1450154874 ?

**Comment by nertzy** [comment]
Yes, that worked for me. Thanks!
